import { useEffect, useMemo, useState } from 'react'
import { NAVIGATION_BY_ROLE } from './config/navigation'
import { ROLE_LABELS, ROLES } from './config/roles'
import { CONTRACT_TYPES } from './config/workflow'
import { getStoredSession, loginWithUsername, logout } from './services/auth'
import './App.css'

const DEMO_DATA = [
  { id: 1, company: 'VIL', project: 'Project A', location: 'Warehouse 01', vendor: 'Demo Vendor', service: 'Manpower', contract: 'Minimum Wages', invNo: 'INV-001', taxable: 100000, amount: 118000, status: 'Pending', stage: 'Warehouse' },
  { id: 2, company: 'VWPL', project: 'Project B', location: 'Warehouse 02', vendor: 'Demo Vendor 2', service: 'Housekeeping', contract: 'Minimum Wages', invNo: 'INV-002', taxable: 75000, amount: 88500, status: 'Submitted', stage: 'GAC — Compliance' },
  { id: 3, company: 'VIL', project: 'Project C', location: 'Warehouse 03', vendor: 'Demo Vendor 3', service: 'Manpower', contract: 'Commercial', invNo: 'INV-003', taxable: 150000, amount: 177000, status: 'Approved for Payment', stage: 'CBO Officer' },
  { id: 4, company: 'VWPL', project: 'Project D', location: 'Warehouse 04', vendor: 'Other Vendor', service: 'Other', contract: 'Others', invNo: 'INV-004', taxable: 50000, amount: 59000, status: 'Paid', stage: 'Accounts', utr: 'UTR-DEMO-004' },
]
const ACTIONS = { WH: ['Accept','Query','Return','Reject'], GAC_COMPLIANCE: ['Accept','Query','Return','Reject','Compliance Checked'], GAC_PO: ['Accept','Query','Return','Reject','PO Mapping'], ACCOUNTS: ['Accept','Query','Return','Reject'], CBO_OFFICE: ['Accept','Query','Return','Reject'], CBO_OFFICER: ['Approve','Query','Return','Reject'] }
const money = (n) => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)

function Login({ onLogin }) {
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const submit=async(e)=>{e.preventDefault();setError('');setBusy(true);try{const profile=await loginWithUsername(username,password);onLogin(profile)}catch(err){setError(err.message||'Invalid ID or Password.')}finally{setBusy(false)}}
 return <div className="login-shell"><div className="login-card"><div className="login-brand">GAC</div><div className="login-title">GAC Bill Payment Portal</div><p className="login-subtitle">P2V2 secure sign-in</p>{error&&<div className="notice login-error">{error}</div>}<form onSubmit={submit}><label>User ID<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} placeholder="Enter User ID" autoFocus/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter Password"/></label><button className="primary login-button" disabled={busy||!username||!password}>{busy?'Signing in…':'Login'}</button></form></div></div>
}

function App(){
 const [session,setSession]=useState(()=>getStoredSession()),[active,setActive]=useState('Dashboard'),[search,setSearch]=useState(''),[company,setCompany]=useState('All'),[type,setType]=useState('All'),[data,setData]=useState(DEMO_DATA),[notice,setNotice]=useState('')
 useEffect(()=>{if(session?.profile?.role) setActive('Dashboard')},[session])
 if(!session?.profile) return <Login onLogin={profile=>setSession(getStoredSession()||{profile})}/>
 const role=session.profile.role
 const nav=NAVIGATION_BY_ROLE[role]||NAVIGATION_BY_ROLE[ROLES.ADMIN]
 const filtered=useMemo(()=>data.filter(x=>`${x.invNo} ${x.vendor} ${x.project} ${x.location}`.toLowerCase().includes(search.toLowerCase())&&(company==='All'||x.company===company)&&(type==='All'||x.contract===type)),[data,search,company,type])
 const action=(id,a)=>{const status=a==='Approve'?'Approved for Payment':a==='Compliance Checked'?'Compliance Checked':a==='Accept'?'Accepted':a==='PO Mapping'?'PO Mapped':a;setData(data.map(x=>x.id===id?{...x,status}:x));setNotice(`${a} recorded. Workflow history must retain remarks and exact timestamp.`)}
 const submit=(x)=>{setData([{...x,id:Date.now(),status:'Pending',stage:'Warehouse'},...data]);setNotice('Invoice submitted to Warehouse.')}
 const handleLogout=async()=>{await logout();setSession(null);setNotice('')}
 return <div className="app-shell"><header className="topbar"><div className="brand-mark">GAC</div><div className="portal-title">GAC Bill Payment Portal</div><div className="user-area">{session.profile.display_name||session.profile.username} • {ROLE_LABELS[role]||role}<button className="logout" onClick={handleLogout}>Logout</button></div></header>
  <div className="workspace"><aside className="sidebar"><div className="side-label">MENU</div>{nav.map(x=><button key={x} className={`nav-item ${active===x?'active':''}`} onClick={()=>setActive(x)}>{x}</button>)}</aside>
   <main className="content"><div className="toolbar"><input placeholder="Search invoice, vendor, project or location" value={search} onChange={e=>setSearch(e.target.value)}/><select value={company} onChange={e=>setCompany(e.target.value)}><option>All</option><option>VIL</option><option>VWPL</option></select><select value={type} onChange={e=>setType(e.target.value)}><option>All</option>{CONTRACT_TYPES.map(x=><option key={x}>{x}</option>)}</select></div>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}{active==='Dashboard'?<Dashboard data={data} filtered={filtered} actions={ACTIONS[role]||[]} onAction={action}/>:active==='Submit Invoice'?<SubmitInvoice onSubmit={submit}/>:<InvoiceTable title={active} data={filtered} actions={ACTIONS[role]||[]} onAction={action}/>}</main></div><footer>All Rights Reserved © 2026 GAC Bill Payment Portal</footer></div>
}
function Dashboard({data,filtered,actions,onAction}){const n=s=>data.filter(x=>x.status===s).length;return <><section className="hero-panel"><div><span className="eyebrow">P2V2 WORKFLOW</span><h1>Invoice & Bill Payment Dashboard</h1><p>Current invoice status, workflow actions and payment visibility.</p></div><div className="stage-chip">Live view</div></section><div className="cards"><Metric label="Submitted" value={data.filter(x=>['Submitted','Pending'].includes(x.status)).length}/><Metric label="Pending" value={n('Pending')}/><Metric label="Approved for Payment" value={n('Approved for Payment')}/><Metric label="Paid" value={n('Paid')}/><Metric label="Query / Returned / Rejected" value={data.filter(x=>['Query','Return','Reject'].includes(x.status)).length}/><Metric label="TAT" value="Live"/></div><InvoiceTable data={filtered} actions={actions} onAction={onAction}/></>}
function Metric({label,value}){return <div className="metric"><span>{label}</span><strong>{value}</strong><small>View details →</small></div>}
function InvoiceTable({data,actions,onAction,title='Current Invoice Status'}){return <section className="panel"><div className="panel-heading"><div><h2>{title}</h2><p>{data.length} record(s) in current view</p></div><button className="secondary">Bulk view</button></div><div className="table-wrap"><table><thead><tr><th>Inv No</th><th>Company</th><th>Project / Location</th><th>Vendor</th><th>Service</th><th>Amount</th><th>Status</th><th>Stage</th><th>Action</th></tr></thead><tbody>{data.map(x=><tr key={x.id}><td><b>{x.invNo}</b></td><td>{x.company}</td><td>{x.project}<br/><small>{x.location}</small></td><td>{x.vendor}</td><td>{x.service}<br/><small>{x.contract}</small></td><td>{money(x.amount)}</td><td><span className="status">{x.status}</span>{x.utr&&<small className="utr">UTR: {x.utr}</small>}</td><td>{x.stage}</td><td>{actions.length?<select defaultValue="" onChange={e=>e.target.value&&onAction(x.id,e.target.value)}><option value="">Select</option>{actions.map(a=><option key={a}>{a}</option>)}</select>:<button className="link-btn">View</button>}</td></tr>)}</tbody></table></div></section>}
function SubmitInvoice({onSubmit}){const [f,setF]=useState({company:'VIL',project:'',location:'',vendor:'',invNo:'',taxable:'',amount:''});const u=(k,v)=>setF({...f,[k]:v});const ok=Object.values(f).every(Boolean);return <section className="panel form-panel"><h2>Submit Invoice — Others</h2><p>Vendor-initiated Others route. Invoice is mandatory; supporting documents are optional.</p><div className="form-grid">{[['company','Company'],['project','Project'],['location','Project & Location'],['vendor','Vendor'],['invNo','Inv No'],['taxable','Taxable Amt'],['amount','Amt (Incl GST)']].map(([k,l])=><label key={k}>{l}<input value={f[k]} onChange={e=>u(k,e.target.value)} placeholder={l}/></label>)}<label>Contract Type<select disabled value="Others"><option>Others</option></select></label><label>Invoice Type<select disabled value="Other"><option>Other</option></select></label></div><div className="form-actions"><button disabled={!ok} onClick={()=>onSubmit({...f,taxable:Number(f.taxable),amount:Number(f.amount),contract:'Others',service:'Other'})}>Upload Invoice & Submit</button></div></section>}
export default App
