import { useMemo, useState } from 'react'
import { calculateTat } from '../services/tat'
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')
const monthOf=x=>x.invoice_month||((x.created_at||'').slice(0,7))
const tatDays=t=>{const m=String(t||'').match(/(\d+)d/);return m?Number(m[1]):0}
export default function P2Reports({data,role}){
  const [f,setF]=useState({year:'All',month:'All',company:'All',warehouse:'All',project:'All',vendor:'All',service:'All',sub:'All',present:'All',payment:'All',tatMin:'',tatMax:'',cumMin:'',cumMax:''})
  const vals=k=>[...new Set(data.map(x=>k==='year'?monthOf(x).slice(0,4):k==='month'?monthOf(x).slice(5,7):x[k]).filter(Boolean))].sort()
  const rows=useMemo(()=>data.filter(x=>{const m=monthOf(x);const paid=x.current_status==='PAID';const t=calculateTat({startedAt:x.tat_start_at||x.created_at,endedAt:paid?x.paid_at:null,stageStartedAt:x.stage_started_at||x.created_at});const id=tatDays(t.individual.duration),cu=tatDays(t.cumulative.duration);return (f.year==='All'||m.slice(0,4)===f.year)&&(f.month==='All'||m.slice(5,7)===f.month)&&(f.company==='All'||x.company===f.company)&&(f.warehouse==='All'||x.warehouse===f.warehouse)&&(f.project==='All'||x.project_location===f.project)&&(f.vendor==='All'||x.vendor===f.vendor)&&(f.service==='All'||x.service_type===f.service)&&(f.sub==='All'||x.sub_service===f.sub)&&(f.present==='All'||x.current_status===f.present)&&(f.payment==='All'||(f.payment==='PAID'?paid:!paid))&&(f.tatMin===''||id>=Number(f.tatMin))&&(f.tatMax===''||id<=Number(f.tatMax))&&(f.cumMin===''||cu>=Number(f.cumMin))&&(f.cumMax===''||cu<=Number(f.cumMax))}),[data,f])
  const totals=rows.reduce((a,x)=>{a.submitted++;if(x.current_status==='PAID')a.paid++;else a.pending++;return a},{submitted:0,paid:0,pending:0})
  const download=()=>{const headers=['Invoice Number','Company','Warehouse','Project','Vendor','Service','Sub-category','Invoice Month','Current Status','Current Stage','Amount','Individual TAT','Cumulative TAT','Sunday Count','NH Count'];const body=rows.map(x=>{const t=calculateTat({startedAt:x.tat_start_at||x.created_at,endedAt:x.current_status==='PAID'?x.paid_at:null,stageStartedAt:x.stage_started_at||x.created_at});return [x.inv_no,x.company,x.warehouse,x.project_location,x.vendor,x.service_type,x.sub_service,monthOf(x),x.current_status,x.current_stage,x.amt_incl_gst,t.individual.duration,t.cumulative.duration,t.cumulative.sundays.length,t.cumulative.nationalHolidays.length]});const html=`<html><head><meta charset="utf-8"></head><body><table><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr>${body.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</table></body></html>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'application/vnd.ms-excel'}));a.download='GAC_Bill_Payment_Summary_Report.xls';a.click()}
  const select=(label,key,options)=><label>{label}<select value={f[key]} onChange={e=>setF({...f,[key]:e.target.value})}><option>All</option>{options.map(v=><option key={v}>{v}</option>)}</select></label>
  const num=(label,key)=><label>{label}<input type="number" min="0" value={f[key]} onChange={e=>setF({...f,[key]:e.target.value})}/></label>
  return <section className="panel"><div className="panel-heading"><div><h2>Reports</h2><p>Universal report • {role==='VENDOR'||role==='WH'?'restricted to your mapped invoices':'all accessible invoices'}</p></div><button className="primary" onClick={download}>View / Download Excel</button></div><div className="report-filters">{select('Year','year',vals('year'))}{select('Month','month',vals('month'))}{select('Company','company',vals('company'))}{select('Warehouse','warehouse',vals('warehouse'))}{select('Project','project',vals('project'))}{select('Vendor','vendor',vals('vendor'))}{select('Service','service',vals('service_type'))}{select('Sub-category','sub',vals('sub_service'))}{select('Present Status','present',vals('current_status'))}{select('PAID / Pending','payment',['PAID','Pending'])}{num('Individual TAT min days','tatMin')}{num('Individual TAT max days','tatMax')}{num('Cumulative TAT min days','cumMin')}{num('Cumulative TAT max days','cumMax')}</div><div className="report-summary"><div><b>Month</b><span>{f.year==='All'&&f.month==='All'?'All':`${f.year==='All'?'':f.year}-${f.month==='All'?'':f.month}`}</span></div><div><b>Total Inv Submitted</b><span>{totals.submitted}</span></div><div><b>Total Inv Paid</b><span>{totals.paid}</span></div><div><b>Total Inv Pending</b><span>{totals.pending}</span></div></div><div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Company</th><th>Warehouse</th><th>Project</th><th>Vendor</th><th>Service</th><th>Present Status</th><th>Individual TAT</th><th>Cumulative TAT</th></tr></thead><tbody>{rows.map(x=>{const t=calculateTat({startedAt:x.tat_start_at||x.created_at,endedAt:x.current_status==='PAID'?x.paid_at:null,stageStartedAt:x.stage_started_at||x.created_at});return <tr key={x.id}><td>{x.inv_no||'—'}</td><td>{x.company}</td><td>{x.warehouse}</td><td>{x.project_location}</td><td>{x.vendor}</td><td>{x.service_type}</td><td>{x.current_status}</td><td>{t.individual.duration}</td><td>{t.cumulative.duration}</td></tr>})}</tbody></table>{!rows.length&&<div className="empty-state">No report records match the selected filters.</div>}</div></section>
}
