import { P2_MASTER_MAPPINGS, P2_USERS } from '../data/p2Seed'

// Fresh-test database generation. The previous R&D browser database is intentionally discarded so every browser starts with an empty transaction set while master data/users remain.
const LEGACY_DB_KEY='p2_rnd_database_v1'
const DB_KEY='p2_rnd_database_v2_clean_test'
try{localStorage.removeItem(LEGACY_DB_KEY)}catch{}

const clone=v=>JSON.parse(JSON.stringify(v))
const sessionProfile=()=>{try{const p=JSON.parse(localStorage.getItem('p2v2_auth_session_v4')||'null')?.profile;if(!p)return null;const u=P2_USERS.find(x=>x.username===p.username);return u?{...u,...p}:p}catch{return null}}
const initialState=()=>({users:clone(P2_USERS),vendors:[...new Set(P2_MASTER_MAPPINGS.map(x=>x.vendor))].map((name,i)=>({id:`VEN-${String(i+1).padStart(3,'0')}`,name})),warehouses:[...new Set(P2_MASTER_MAPPINGS.map(x=>x.warehouse))].map((code,i)=>({id:`WH-${String(i+1).padStart(3,'0')}`,code})),vendor_warehouse_map:P2_MASTER_MAPPINGS.map(x=>({id:x.id,organization:x.organization,warehouse:x.warehouse,project_location:x.project_location,vendor:x.vendor,service_type:x.service_type})),bill_requests:[],invoice_records:[],workflow_history:[],pr_po_utr:[],document_records:[]})
function readDb(){try{const db=JSON.parse(localStorage.getItem(DB_KEY)||JSON.stringify(initialState()));for(const k of ['bill_requests','invoice_records','workflow_history','pr_po_utr','document_records'])if(!db[k])db[k]=[];writeDb(db);return db}catch{return initialState()}}
function writeDb(db){localStorage.setItem(DB_KEY,JSON.stringify(db));return db}
function filterRows(rows,q=''){const p=new URLSearchParams(String(q).replace(/^&/,''));return rows.filter(r=>[...p.entries()].filter(([k])=>k!=='order').every(([k,v])=>v.startsWith('eq.')?String(r[k]??'')===decodeURIComponent(v.slice(3)):true))}
function visible(table,rows){const u=sessionProfile();if(!u||u.role==='ADMIN')return rows;const wh=u.warehouses||[];if(table==='invoice_records'||table==='bill_requests'){if(u.role==='VENDOR')return rows.filter(r=>String(r.vendor).toLowerCase()===String(u.display_name||u.username).toLowerCase());if(u.role==='WH')return rows.filter(r=>wh.includes(r.warehouse)||r.current_responsible_user===u.username||r.current_responsible_user===u.display_name)}if(table==='vendors'&&u.role==='VENDOR')return rows.filter(r=>r.name===u.display_name);if(table==='warehouses'&&u.role==='WH')return rows.filter(r=>wh.includes(r.code));if(table==='vendor_warehouse_map'){if(u.role==='VENDOR')return rows.filter(r=>r.vendor===u.display_name&&wh.includes(r.warehouse));if(u.role==='WH')return rows.filter(r=>wh.includes(r.warehouse))}return rows}
const mappingMatches=r=>P2_MASTER_MAPPINGS.some(m=>m.organization===r.organization&&m.warehouse===r.warehouse&&m.project_location===r.project_location&&m.vendor===r.vendor&&m.service_type===r.service_type)
function maxMonth(){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function assertInvoice(db,r){if(!r.inv_no)throw Error('Invoice Number is required.');if(db.invoice_records.some(x=>String(x.inv_no).trim().toLowerCase()===String(r.inv_no).trim().toLowerCase()))throw Error(`Duplicate Invoice Number rejected: ${r.inv_no}`);if(!mappingMatches(r))throw Error('Invalid master mapping.');if(r.service_type==='HK'||r.service_type==='Security'){if(r.contract_type!=='Minimum Wages')throw Error(`${r.service_type} is allowed only under Minimum Wages.`)}else if(r.service_type==='Manpower'&&!['Commercial','Minimum Wages'].includes(r.contract_type))throw Error('Manpower requires Commercial or Minimum Wages contract.');const mm=maxMonth();if(!r.invoice_month||r.invoice_month>mm)throw Error(`Invoice Month cannot be later than ${mm}.`);if(r.route_type==='WH_INITIATED'&&r.invoice_month!==mm)throw Error(`Invoices before ${mm} must use Route 2.`);if(r.route_type==='VENDOR_INITIATED'&&r.invoice_month>=mm)throw Error(`Route 2 is only for invoices before ${mm}.`);const gst=Math.round((Number(r.taxable_amt)||0)*.18*100)/100;if(Math.abs((Number(r.gst_amt)||0)-gst)>.01)throw Error('GST must be exactly 18% of the entered invoice amount.')}
function assertTransition(row,v){const role=sessionProfile()?.role;if(!role||role==='ADMIN')return;const stage=row.current_stage,status=row.current_status,ns=v.current_stage,nst=v.current_status;const remarks=String(v.latest_remarks??'').trim();const fail=m=>{throw Error(`Workflow gate failed: ${m}`)};if(stage!==({WH:'WH',GAC_COMPLIANCE:'GAC_COMPLIANCE',GAC_PO:'GAC_PO',ACCOUNTS:'ACCOUNTS',CBO_OFFICE:'CBO_OFFICE',CBO_OFFICER:'CBO_OFFICER',VENDOR:'VENDOR'}[role]||stage))fail(`only ${role} may action this stage`)
 if(nst==='REJECTED'&& !remarks)fail('Remarks are mandatory when an invoice is rejected')
 if(role==='VENDOR'&&status==='RETURNED'&&ns==='WH'&&nst==='SUBMITTED')return
 if(role==='WH'&&status==='SUBMITTED'&&ns==='WH'&&nst==='ACCEPTED')return
 if(role==='WH'&&status==='ACCEPTED'&&ns==='WH'&&nst==='ACCEPTED')return
 if(role==='WH'&&status==='ACCEPTED'&&ns==='GAC_COMPLIANCE'&&nst==='PR_MAPPED')return
 if(role==='WH'&&status==='SUBMITTED'&&ns==='GAC_COMPLIANCE'&&nst==='PR_MAPPED')return
 if(role==='WH'&&status==='RETURNED'&&ns==='GAC_COMPLIANCE'&&nst==='PR_MAPPED')return
 if(role==='GAC_COMPLIANCE'&&['SUBMITTED','PR_MAPPED'].includes(status)&&ns==='GAC_COMPLIANCE'&&nst==='ACCEPTED')return
 if(role==='GAC_COMPLIANCE'&&['ACCEPTED','UNDER_COMPLIANCE_CHECK'].includes(status)&&ns==='GAC_PO'&&nst==='COMPLIANCE_CHECKED')return
 if(role==='GAC_COMPLIANCE'&&['ACCEPTED','UNDER_COMPLIANCE_CHECK'].includes(status)&&['WH','VENDOR'].includes(ns)&&['RETURNED','REJECTED'].includes(nst))return
 if(role==='GAC_PO'&&status==='COMPLIANCE_CHECKED'&&ns==='ACCOUNTS'&&nst==='PO_MAPPED')return
 if(role==='ACCOUNTS'&&status==='PO_MAPPED'&&ns==='CBO_OFFICE'&&nst==='SUBMITTED')return
 if(role==='CBO_OFFICE'&&status==='SUBMITTED'&&ns==='CBO_OFFICER'&&nst==='SUBMITTED')return
 if(role==='CBO_OFFICER'&&status==='SUBMITTED'&&ns==='ACCOUNTS'&&nst==='APPROVED_FOR_PAYMENT')return
 if(role==='ACCOUNTS'&&status==='APPROVED_FOR_PAYMENT'&&ns==='ACCOUNTS'&&nst==='PAID')return
 if(['QUERY','RETURNED','REJECTED'].includes(nst)){const d={WH:['VENDOR'],GAC_COMPLIANCE:['VENDOR','WH'],GAC_PO:['VENDOR','WH'],ACCOUNTS:['GAC_PO'],CBO_OFFICE:['ACCOUNTS','GAC_PO','WH','VENDOR'],CBO_OFFICER:['CBO_OFFICE','ACCOUNTS','GAC_PO','WH','VENDOR']}[role]||[];if(!d.includes(ns))fail(`invalid destination ${ns}`);return}fail(`${role} cannot change ${stage}/${status} to ${ns}/${nst}`)}
export async function selectRows(table,q=''){const db=readDb();if(!db[table])throw Error(`Unknown P2 database table: ${table}`);let r=visible(table,filterRows(db[table],q));if(new URLSearchParams(String(q).replace(/^&/,'')).get('order')==='created_at.desc')r=[...r].sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')));return clone(r)}
export async function insertRows(table,rows){const db=readDb();if(!db[table])throw Error(`Unknown P2 database table: ${table}`);const input=Array.isArray(rows)?rows:[rows];for(const r of input){if(table==='invoice_records')assertInvoice(db,r);if(table==='pr_po_utr'&&r.pr_number&&!['WH','ADMIN'].includes(sessionProfile()?.role))throw Error('Only Warehouse can map PR.');if(table==='pr_po_utr'&&r.po_number&&!['GAC_PO','ADMIN'].includes(sessionProfile()?.role))throw Error('Only GAC PO can map PO.');if(table==='pr_po_utr'&&r.utr_number&&!['ACCOUNTS','ADMIN'].includes(sessionProfile()?.role))throw Error('Only final Accounts can map UTR.')}const out=input.map(r=>({id:r.id||`ID-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,created_at:r.created_at||new Date().toISOString(),...r}));db[table].push(...clone(out));writeDb(db);return clone(out)}
export async function updateRows(table,q,v){const db=readDb();if(!db[table])throw Error(`Unknown P2 database table: ${table}`);const hits=filterRows(db[table],q);if(table==='invoice_records'&&(v.current_stage||v.current_status)){if(hits.length!==1)throw Error('Workflow update must target exactly one invoice.');const merged={...hits[0],...v};assertTransition(hits[0],merged)}const out=[];db[table]=db[table].map(r=>{if(!filterRows([r],q).length)return r;const x={...r,...v};out.push(x);return x});writeDb(db);return clone(out)}
export async function deleteRows(table,q){const db=readDb();if(!db[table])throw Error(`Unknown P2 database table: ${table}`);db[table]=db[table].filter(r=>!filterRows([r],q).length);writeDb(db);return []}
export function resetRDatabase(){localStorage.removeItem(DB_KEY);return initialState()}
export const supabaseConfigured=false
export const RD_MODE=true
